[package]
name = "sniff-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pcap = { version = "1.1.0", features = ["capture-stream"] }
thiserror = "1.0.48"

[dev-dependencies]
mockall = "0.11.4"

